spring.application.name=eventos-utp

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Eventos_UTP
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
